# Base Jekyll configuration

# Use _config.build.yml to override these settings on `grunt build`.

name: hugobessa
url: http://192.168.1.16:3000


# Theme options
title: Hugo Bessa
description: front-end mad scientist and collaboration enthusiast


# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess', 'favicon.png', 'favicon_facebook.png', 'apple-touch-icon-precomposed.png']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: /posts/:title/

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Split posts over multiple subdirectories called “page/2”, “page/3”, … “page/N”
paginate: 10
paginate_path: 'page/:num'

excerpt_separator: <!--more-->

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: [
    'no_intra_emphasis',
    'fenced_code_blocks',
    'smart',
    'autolink',
    'tables',
    'with_toc_data'
  ]

# Use Pygments to highlight code blocks
pygments: true

# Base url is for assets. Full url is for non-relative urls, such as Facebook meta tags
baseurl:
fullurl: http://192.168.1.16:3000

category_archive:
  slugify: true
  layout: default
  path: /categoria